spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hrms-service
              uri: ${HRMS_URI}
              predicates:
                - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG