spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hrms-service
              uri: ${HRMS_URI}
              predicates:
                - Path=/**

jwt:
  secretKey: ${JWT_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG